name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  standard:
    name: "Standard"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "ruby"
          bundler-cache: true
      - run: bundle exec rake standard
  build:
    name: "Test / Ruby ${{ matrix.ruby }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ["3.3", "3.4"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby & Rust
        uses: oxidize-rb/actions/setup-ruby-and-rust@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          cargo-cache: true
          rubygems: '3.5.22'
      - name: Run the default task
        run: bundle exec rake
      - name: Test
        run: bundle exec rake spec